# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Given a (nano)arrow array external pointer object via two pointers (with the second tucked
#' away as the tag), return an arma vector
#'
#' @section Limitations:
#' As this aims at \pkg{armadillo} interoperation, this functionality is limited to numeric
#' vector columns. The framework used here could of course be extended to other Arrow formats.
#'
#' @param vec A nanoarrow array object as an external pointer
#' @param verbose A logical value, default is false
#' @examples
#' sv <- nanoarrow::as_nanoarrow_array(c(4:7), nanoarrow::na_int16())  # internally int16
#' armaVectorExample(sv)
armaVectorExample <- function(vec, verbose = FALSE) {
    .Call(`_naarma_armaVectorExample`, vec, verbose)
}

#' Given a (nano)arrow object via two pointers, and a column size, return an arma matrix
#'
#' @section Limitations:
#' As this aims at \pkg{armadillo} operations, this functionality is limited to numeric
#' vector columns. The framework used here could of course be extended to other Arrow formats.
#'
#' @param vec A nanoarrow object
#' @param ncol Number of columns in returned matrix
#' @param verbose A logical value, default is false
#' @examples
#' sv <- nanoarrow::as_nanoarrow_array(c(4:8), nanoarrow::na_int16())  # internally int16
#' armaMatrixExample(sv, 2)
armaMatrixExample <- function(vec, ncol, verbose = FALSE) {
    .Call(`_naarma_armaMatrixExample`, vec, ncol, verbose)
}

#' Given a (nano)arrow stream object pointer, return an arma matrix
#'
#' @section Limitations:
#' As this aims at \pkg{armadillo} operation, the returned matrix is always double while
#' supported many possible column types.
#'
#' @param obj A nanoarrow array stream object via an external pointer
#' @param verbose A logical value, default is false
collectMatrixFromStream <- function(obj, verbose = FALSE) {
    .Call(`_naarma_collectMatrixFromStream`, obj, verbose)
}

